### ISSUE TITLE
READ NOW

### ISSUE THREAD

**Issue by KowlinMC** [joshuapatel/GordonRamsay#4]
Friend me KowlinMC#2385 @joshuapatel immediately.

**Comment by joshuapatel** [comment]
I know. The guild is deleted and my account got banned.

**Comment by KowlinMC** [comment]
I fucking hate discord staff

**Comment by joshuapatel** [comment]
My 6th Discord account ban eh?

**Comment by KowlinMC** [comment]
My first Discord account ban eh? >:(

**Comment by KowlinMC** [comment]
And of course the gordon bot is on a team so I can't access it

**Comment by KowlinMC** [comment]
I knew something would fuck this up

**Comment by KowlinMC** [comment]
If I could mention discord staff and tell them to go fuck themselves without getting my new account banned I would.

**Comment by KowlinMC** [comment]
I'm going to create a new guild and invite you.

**Comment by joshuapatel** [comment]
My account is disabled.

**Comment by KowlinMC** [comment]
I know

**Comment by KowlinMC** [comment]
Create a new account and i'll send you an invite on here.

**Comment by joshuapatel** [comment]
I'm eating lunch right now so I'm not home. Anyways, my IP address is most likely blacklisted. I could use the alt that I told you about, but I'm not sure if it's been banned.

**Comment by joshuapatel** [comment]
I opened the Discord app and saw it go back to the login screen.

**Comment by joshuapatel** [comment]
that's when i knew i was fucked

**Comment by joshuapatel** [comment]
request all of your information from discord

**Comment by A-Trash-Coder** [comment]
Im surprised i wasnt banned

**Comment by A-Trash-Coder** [comment]
Hope im not next

**Comment by joshuapatel** [comment]
you are so fucking lucky that we banned you yesterday

**Comment by A-Trash-Coder** [comment]
im kinda glad now ngl

**Comment by joshuapatel** [comment]
you're welcome

**Comment by A-Trash-Coder** [comment]
thanks

**Comment by A-Trash-Coder** [comment]
i still love you

**Comment by joshuapatel** [comment]
i'm not sure about the timed mute command now...

**Comment by KowlinMC** [comment]
Why?

**Comment by joshuapatel** [comment]
well at least probably won't be able to get it done by 9:30 tonight

**Comment by joshuapatel** [comment]
because y'know

**Comment by joshuapatel** [comment]
just got banned

**Comment by A-Trash-Coder** [comment]
lmao

**Comment by KowlinMC** [comment]
https://discord.gg/SW7bmXm

**Comment by joshuapatel** [comment]
time to reset my IP address

**Comment by A-Trash-Coder** [comment]
can i join Kowlin?

**Comment by A-Trash-Coder** [comment]
and not be a dick

**Comment by KowlinMC** [comment]
sure idc at this point

**Comment by joshuapatel** [comment]
i'm waiting until i get on my pc to make a new account and join

**Comment by joshuapatel** [comment]
sadly i'm still eating out

**Comment by A-Trash-Coder** [comment]
jill?
